version: '3.9'

networks:
  law-finder-network:
    driver: bridge

x-common-postgres-environment: &common-postgres-environment
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: law-finder
  POSTGRES_DB_URL: jdbc:postgresql://law-finder-db:5432/law-finder

services:
  law-finder-db:
    container_name: law-finder-db
    image: guachallasergio/law-finder-db:1.1

    ports:
      - 5433:5432
    volumes:
      - ./src/main/resources/init_3.sql:/docker-entrypoint-initdb.d/create_database.sql
      - ./docker/bd/data:/var/lib/postgresql/data &&  sudo chmod 0700 /var/lib/postgresql/data
    environment:
        <<: *common-postgres-environment
    build: .
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr",
        "-c",
        "shared_preload_libraries=pg_cron",
        "-c",
        "cron.database_name=law-finder",
      ]
    networks:
        - law-finder-network

  mailhog:
      image: mailhog/mailhog
      container_name: 'mailhog'
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
          - law-finder-network

  lawfinder-backend:
    container_name: lawfinder-backend
    image: guachallasergio/lawfinder-backend:latest
    ports:
      - "8080:8080"
    environment:
      <<: *common-postgres-environment
    restart: always
    depends_on:
      - law-finder-db
      - mailhog
    networks:
        - law-finder-network
