spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/law_finder_test
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: law.finder.ucb@gmail.com
    password: zxtgwqffbbgubfbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

