server:
  port: 8080
spring:
  application:
    name: law-finder
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5434/law-finder}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  # sql:
  #   init:
  #     mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: law.finder.ucb@gmail.com
#    password: zxtgwqffbbgubfbg
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: law.finder.ucb@gmail.com
    password: password