
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pruebita
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: law.finder.ucb@gmail.com
#    password: zxtgwqffbbgubfbg
  mail:
    host: localhost
    port: 1025
    username: law.finder.ucb@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
