GET http://localhost:8080/api/v1/department
###
GET http://localhost:8080/api/v1/department/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsYXdmaW5kZXIuY29tIiwibmFtZSI6InVzdWFyaW9zcyIsInR5cGUiOiJBVVRIIiwiZXhwIjoxNjg0ODg2ODg1LCJ1c2VySWQiOjN9.NaQvVkEehTWxb4_bzs5mK017H-zn9icl6KBt2xmHjmc

###
GET http://localhost:8080/api/v1/department/5/province
