
###
POST http://localhost:8080/api/v1/legalcase
Content-Type: application/json
Accept: application/json

{
    "userId": 16,
    "idSubCategory": 2,
    "idProvince": 3,
    "idCrime": 1,
    "contrapart": "Parte sin conasd3232",
    "title": "Caso Legal 2022",
    "startDate": "2023-05-23",
    "summary": "........caso.....",
    "idInstance": 1,
    "startDateInstance": "2023-05-23",
    "endDateInstance": "2023-05-23"
}

###
GET http://localhost:8080/api/v1/category/1/subcategory

###
GET http://localhost:8080/api/v1/legalcase/instance

###
GET http://localhost:8080/api/v1/legalcase/user/6

###
GET http://localhost:8080/api/v1/case/28/files

###
GET http://localhost:8080/api/v1/legalcase/user/15

###
POST http://localhost:8080/api/v1/userverification
Content-Type: application/json
Accept: application/json

{
    "email": "aleayalafa@gmail.com"

}

###
GET http://localhost:8080/api/v1/instanceLegal/8

###

GET http://localhost:8080/api/v1/legalcase/26/information