GET http://localhost:8080/api/v1/users
###
PUT http://localhost:8080/api/v1/users/3
###
POST http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: application/json

{
    "username": "usuarios_testo22",
    "secret": "1234aa",
    "status": 1,
    "personId": {
        "name": "ale",
        "ci": "123456789",
        "ciExpedition": "",
        "lastname": "que haces",
        "number": "123456789",
        "email": "idontevenplaymm@gmail.com",
        "address": "calle 1234"
    },
    "ImageId": 0
}
