GET http://localhost:8080/api/v1/user

###
POST http://localhost:8080/api/v1/user
Content-Type: application/json
Accept: application/json

{
    "username": "usuarios_testo32",
    "secret": "1234",
    "status": false,
    "personId": {
        "personId": 1,
        "name": "ale",
        "lastname": "que haces",
        "number": "123456789",
        "email": "idontevenplaymm@gmail.com",
        "address": {
            "addressInfo": "Villa sexo69",
            "provId": 1
        }
    },
    "ImageId": 0
}
