POST http://localhost:8080/api/v1/sendmail
Content-Type: application/json
Accept: application/json

{
   "mail":"polfaalejandro@gmail.com"
}

###

POST http://localhost:8080/api/v1/verify
Content-Type: application/json
Accept: application/json

{
   "mail":"polfaalejandro@gmail.com",
   "token":"857480"
}
